# Пример конфигурации для конвейера обработки видео
input: input.mp4      # Путь к входному видео
output: output.mp4    # Путь к выходному видео

# Список модулей обработки (применяются последовательно)
modules:
  # Изменение размера видео
  - name: resize
    params:
      width: 1280        # Ширина в пикселях
      height: 720        # Высота в пикселях
      keep_aspect_ratio: true   # Сохранять пропорции при изменении размера
  
  # Добавление водяного знака
  - name: watermark
    params:
      image_path: logo.png   # Путь к изображению водяного знака
      position: bottomright  # Позиция (topleft, topright, bottomleft, bottomright, center)
      opacity: 0.7           # Прозрачность (0.0-1.0)
      scale: 0.15            # Масштаб относительно размера видео (0.0-1.0) 