# Пример конфигурации для конвейера обработки видео
input: "velo.mp4"
output: "output.mp4"  # Это значение будет перезаписано параметрами модуля cut

# Список модулей обработки (применяются последовательно)
modules:
  - name: utility.cut
    params:
      duration: 40  # Длительность каждой части в секундах
      output_dir: "workspace/velosiped/velo_parts"
      use_input_name: true  # Использовать имя входного файла как префикс




