# Пример конфигурации для конвейера обработки видео
input: "workspace/pornushka/TEMP/2.mp4"
output: "output.mp4"

# Список модулей обработки (применяются последовательно)
modules:
  - name: "resize"
    params:
      width: 540
      height: 960

  # Расширение видео с изображением в качестве фона
  - name: "pad"
    params:
      width: 1080
      height: 1920
      position: "center_left"
      image_path: "workspace/pornushka/back.png"  # Путь к изображению для фона

  # Добавление зацикленного видео без звука
  - name: "addvideo"
    params:
      video_path: "workspace/pornushka/TEMP/1.mp4"
      position: "center_right"
      width: 540       # Ширина в пикселях
      height: 960      # Высота в пикселях
      loop: true       # Зацикливать видео до конца основного
      mute: true       # Удалить звук из добавляемого видео
  - name: "utility.prepareforyt"




