input: "input.mp4"
output: "output.mp4"
modules:
- name: "resize"
  params:
    width: 1920
    height: 1080
    keep_aspect_ratio: true
    audio_codec: "copy"
- name: "watermark"
  params:
    image_path: "watermark.png"
    position: "bottomright"
    opacity: 0.7
    scale: 0.2
    audio_codec: "copy"
- name: "deleteaudio"
  params: {}
- name: "crop"
  params:
    position: "center"
    width: 1280
    height: 720
    x: 0
    y: 0
    audio_codec: "copy"
- name: "pad"
  params:
    width: 1920
    height: 1080
    position: "center"
    color: "black"
    image_path: "background.jpg"
    audio_codec: "copy"
- name: "addvideo"
  params:
    video_path: "overlay.mp4"
    position: "center"
    x: 0
    y: 0
    width: 640
    height: 360
    scale: 1.0
    alpha: 1.0
    start_time: 0
    end_time: 5
    loop: false
    mute: true
- name: "chromakey"
  params:
    color: ["green"]
    similarity: [0.1]
    blend: [0.0]
    yuv: false
    overlay: "greenscreen.mp4"
    position: "center"
    scale: 1.0
    audio_codec: "copy"
    mute_overlay: true
- name: "utility.cut"
  params:
    duration: 60
    output_dir: "parts"
    prefix: "part_"
    use_input_name: false
- name: "utility.prepareforyt"
  params: {}
- name: "text_effects"
  params:
    text: "Привет, мир!"
    font: "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
    font_size: 72
    color: "white"
    position: "center"
    effect: "shake"
    effect_intensity: 7
    start_time: 2
    duration: 5
    outline_color: "black"
    outline_width: 3
